name: erek_dash
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+2

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  flutter_launcher_icons: ^0.13.1
  flutter_treeview: ^1.0.7+1
  google_sign_in: ^6.1.6
  google_sign_in_web: ^0.12.3+1
  path_provider: ^2.0.15
  permission_handler: ^11.1.0
  sqflite: ^2.2.8+4
  path: ^1.8.3
  flutter_staggered_grid_view: ^0.7.0
  image_picker: ^1.0.2
  intl: ^0.19.0 
  firebase_core: ^2.24.2
  firebase_app_check: ^0.2.1+8
  firebase_auth: ^4.9.0
  firebase_auth_web: ^5.8.9
  firebase_storage: ^11.2.6
  firebase_database: ^10.2.5

  cupertino_icons: ^1.0.2

flutter_icons:
  image_path: "assets/launchicon/erekdashicon.png"  
  android: true
  ios: true

dev_dependencies:

  flutter_lints: ^3.0.1


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

