create table tasks (
id integer primary key autoincrement, 
task varchar(100),
created_time date, 
updated_time date, 
starting_time date,
pinned_time date,
spending_time smallint, 
finished_time date,
overdue_time smallint,
added_time smallint,
saved_time smallint,
importancy smallint, 
ongoing boolean, 
label smallint,
active boolean,
subtask boolean,
parent_task_id smallint,
conditional_task boolean,
conditional_task_id smallint,
note varchar(150),
on_others boolean,
is_money_in boolean, 
done boolean,
done_it boolean
)